### ISSUE TITLE
Lost custom CURLOPT_HTTPHEADER headers in \Sabre\HTTP\Client

### ISSUE THREAD

**Issue by tigokr** [fruux/sabre-http#52]
If i set custom CURLOPT_HTTPHEADER in \Sabre\HTTP\Client:426 them purged.

        if(isset($settings[CURLOPT_HTTPHEADER]))
            $settings[CURLOPT_HTTPHEADER] = array_merge((array)$settings[CURLOPT_HTTPHEADER], $nHeaders);
        else
            $settings[CURLOPT_HTTPHEADER] = $nHeaders;

**Comment by evert** [comment]
You should do this with `setHeader()` instead.

**Comment by tigokr** [comment]
i use it with \Sabre\DAV\Client like this 

        $client->addCurlSetting(CURLOPT_HTTPHEADER, [
            'Authorization: OAuth '.$this->token, // https://tech.yandex.ru/disk/doc/dg/concepts/quickstart-docpage/
            'Accept: */*',
            'Host: webdav.yandex.ru'
        ]);

**Comment by evert** [comment]
There's a more appropriate way to do this:

```php
$client->on('beforeRequest', function($request) {

   $request->setHeader('Authorization', 'OAuth ' . 'etc...');

});

**Comment by tigokr** [comment]
like magic =) thanks

**Comment by evert** [comment]
And the nice thing is, you can also intercept the `error:401` event, refresh your oauth token and retry with a new header. All built-in =)
