### ISSUE TITLE
sending json

### ISSUE THREAD

**Issue by bazo** [fruux/sabre-http#58]
im building a podio client, which accepts json in post requests

so i put a json string in request body and expected it to work
then i wasted some time thinking podio is stupid, until i pasted the json in postman and sent it as raw json

to my surprise it worked

and as i look at your code, sabre doesn't allow this, because it automatically sets boy as postfields which is useless

**Comment by bazo** [comment]
sorry, it was something else. your client is very good!

**Comment by evert** [comment]
Glad to hear it!
