### ISSUE TITLE
Basic auth: use UTF-8 by default

### ISSUE THREAD

**Issue by rfc2822** [fruux/sabre-http#69]
In the past (since RFC 2617), there have been difficulties with non-US-ASCII characters in Basic auth credentials. Some clients use ISO-8859-1, some use UTF-8, and so on the server side. In reality, only US-ASCII characters are usable expect for proprietary solutions where clients and servers are tailored together.

Since RFC 7617, it's clear that UTF-8 is the future.

* `requireLogin()`: Please send `Basic realm="…",charset="UTF-8"` (see RFC 7617) on the server side in the 401 response, so that clients know that the server expects UTF-8 credentials.
* `getCredentials()`: Make sure that UTF-8 credentials are understood correctly.

**Comment by rfc2822** [comment]
Thanks :)

**Comment by mbiebl** [comment]
Hi,
it seems this fix never made it into the stable 4.2 branch. Would it be possible to cherry-pick this commit and make a 4.2.4 release?

**Comment by DeepDiver1975** [comment]
@mbiebl here we go - https://github.com/sabre-io/http/pull/91/files

**Comment by DeepDiver1975** [comment]
> Could we just release 4.2.4 with this one change?

why not - @staabm any objections?

**Comment by DeepDiver1975** [comment]
preparing release in here https://github.com/sabre-io/http/pull/96 ...

**Comment by DeepDiver1975** [comment]
@mbiebl here we go - https://github.com/sabre-io/http/releases/tag/4.2.4
