### ISSUE TITLE
http 2 doesn't get recognized

### ISSUE THREAD

**Issue by jens1o** [fruux/sabre-http#81]
It falls back to 1.1.
https://github.com/fruux/sabre-http/blob/master/lib/Sapi.php#L134-L136

Happy to provide a pr when you want it to be fixed.

**Comment by staabm** [comment]
will the http2 binary protocol deliver this values as 1.0/1.1 did?

or will those values only be provided with http2 over plain-text?

**Comment by jens1o** [comment]
I'm talking about the httpVersion. So the headers are the same:
![image](https://user-images.githubusercontent.com/11234139/27441991-51b2a740-576f-11e7-9b0c-0147a989e7ae.png)
But `sabre-http` does not recognize it is in http 2.

**Comment by jens1o** [comment]
any news on this? This is pretty important to me.

**Comment by staabm** [comment]
Pr welcome incl. test welcome

**Comment by jens1o** [comment]
Okay, will work on it. :)

**Comment by staabm** [comment]
Ok will close for now
